### ISSUE TITLE
[Feat]: Profile Command

### ISSUE THREAD

**Issue by Sonichigo** [Alphasians/AinaBot#32]
### Detailed Description

Profile Command Should Show rank wallet and etc in card form!

### Contributing

- [X] I have read the project's contribution guidelines.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krishguptadev** [comment]
Can I work on this? 😄

**Comment by Sonichigo** [comment]
Sure sure!!
