### ISSUE TITLE
Adding Documentation of the BOT

### ISSUE THREAD

**Issue by Sonichigo** [Alphasians/AinaBot#4]
## Documenting The Project!

Based on the following the features:

- [x] Music Commands - Play, Skip, Stop, Resume, Queue.
- [x] Mod Commands - Kick, Ban.
- [ ] Level Commands
- [ ] Misc Commands

Once you have completed the documentation of the specific feature, we will mark it as complete!

**Comment by Ameen-Here** [comment]
Can I take up the issue?

**Comment by Ameen-Here** [comment]
Should I need to give the documentation, inside the code or readme file.
And whatt all documentation should be completed?

**Comment by Sonichigo** [comment]
@Ameen-Here 
U can make a folder named doc and add the documentation there in readme file!!
It's preferable to add both but if u chose only one then also it's fine

**Comment by warunicorn19** [comment]
@Ameen-Here any updates on this?
